version: '3'

services:
  demyo:
    image: demyo:3.1.0
    build:
      context: ../../source
      dockerfile: ../integration/docker/Dockerfile
      args:
        GITHUB_PKG_TOKEN: ${GITHUB_PKG_TOKEN}
    ports:
      - 8080:8080
    volumes:
      - demyo-data:/demyo-data

volumes:
  demyo-data:
