language: java
# Needed for openjdk8
dist: trusty
jdk:
  - oraclejdk7
  - oraclejdk8
  - openjdk7
  - openjdk8
# Demyo sources are in a sub-directory
before_script:
  cd source
cache:
  directories:
    - $HOME/.m2
