language: java
# Needed for openjdk8
dist: xenial
jdk:
  - oraclejdk8
  - openjdk8
# Demyo sources are in a sub-directory
before_script:
  cd source
# The standard script does not run integration tests
script:
  mvn verify -B
cache:
  directories:
    - $HOME/.m2
