demyo:
    meta:
        version: @project.version@
        codename: @project.versionCodename@

spring:
    application:
        name: Demyo
    jpa:
        show-sql: @config.hibernate.debug@
        open-in-view: false
        properties:
            hibernate:
                format_sql: @config.hibernate.debug@
    devtools:
        restart:
              additional-paths:
                  - ../demyo-common
                  - ../demyo-dao
                  - ../demyo-model
                  - ../demyo-service
                  - ../demyo-utils
                  - ../demyo-web
#TODO: #205: Restrict this to local dev, use exclude by default
management:
    endpoints:
        web:
            exposure:
                include: '*'
