# TODO: #205: We should use profiles for this
spring:
    jpa:
        show-sql: @config.hibernate.debug@
        open-in-view: false
        properties:
            hibernate:
                format_sql: @config.hibernate.debug@
    devtools:
        restart:
              additional-paths:
                  - ../demyo-common
                  - ../demyo-dao
                  - ../demyo-model
                  - ../demyo-service
                  - ../demyo-utils
                  - ../demyo-web
