/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AlbumCard: typeof import('./src/components/AlbumCard.vue')['default']
    AlbumTextList: typeof import('./src/components/AlbumTextList.vue')['default']
    AppSnackbar: typeof import('./src/components/AppSnackbar.vue')['default']
    AppTask: typeof import('./src/components/AppTask.vue')['default']
    AppTasks: typeof import('./src/components/AppTasks.vue')['default']
    AutoComplete: typeof import('./src/components/AutoComplete.vue')['default']
    CardTextIndex: typeof import('./src/components/CardTextIndex.vue')['default']
    CurrencyField: typeof import('./src/components/CurrencyField.vue')['default']
    DnDImage: typeof import('./src/components/DnDImage.vue')['default']
    Fab: typeof import('./src/components/Fab.vue')['default']
    FavouriteButton: typeof import('./src/components/FavouriteButton.vue')['default']
    FieldValue: typeof import('./src/components/FieldValue.vue')['default']
    FormActions: typeof import('./src/components/FormActions.vue')['default']
    GalleryIndex: typeof import('./src/components/GalleryIndex.vue')['default']
    ItemCardPagination: typeof import('./src/components/ItemCardPagination.vue')['default']
    LetterIcon: typeof import('./src/components/LetterIcon.vue')['default']
    MetaSeriesCard: typeof import('./src/components/MetaSeriesCard.vue')['default']
    MetaSeriesIndex: typeof import('./src/components/MetaSeriesIndex.vue')['default']
    ModelLink: typeof import('./src/components/ModelLink.vue')['default']
    PriceManagement: typeof import('./src/components/PriceManagement.vue')['default']
    PriceTable: typeof import('./src/components/PriceTable.vue')['default']
    PublisherCard: typeof import('./src/components/PublisherCard.vue')['default']
    QuickSearchResults: typeof import('./src/components/QuickSearchResults.vue')['default']
    ReaderSelection: typeof import('./src/components/ReaderSelection.vue')['default']
    RichTextEditor: typeof import('./src/components/RichTextEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionCard: typeof import('./src/components/SectionCard.vue')['default']
    TagLink: typeof import('./src/components/TagLink.vue')['default']
    TextIndex: typeof import('./src/components/TextIndex.vue')['default']
  }
}
